{% set name = "cclib" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d10aa2352479fcdaa86cc32055a8ae7f98ce26523ea928944ab2256f0875d605

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - ccframe = cclib.scripts.ccframe:main
    - ccget = cclib.scripts.ccget:ccget
    - ccwrite = cclib.scripts.ccwrite:main
    - cda = cclib.scripts.cda:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.2.0
    - packaging >=19.0
    - pandas
    - periodictable
    # all of the following are optional
    # - ase >=3.2.1
    # - biopython
    # - openbabel
    # - psi4
    # - pyquante2 (not yet available on conda-forge)
    # - pyscf
    # - qc-iodata (not yet available on conda-forge)

test:
  requires:
    - python {{ python_min }}
  imports:
    - cclib
  commands:
    - ccframe --help
    - ccget --help
    - ccwrite --help
    - python -c 'import cclib; print(cclib.__version__)'
    - python -c 'from cclib.io import ccread; data = ccread("https://raw.githubusercontent.com/cclib/cclib-data/master/Gaussian/Gaussian16/water.log"); print(data.zpve)'
  downstreams:
    # - morfeus-ml (missing pkg_resources dependency)
    - quacc
    # - rmg (not on conda-forge, located at https://anaconda.org/rmg/rmg but not updated)

about:
  home: http://cclib.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parsers and algorithms for computational chemistry logfiles
  description: |
    cclib is a Python library that provides parsers for output files of
    computational chemistry packages. It also provides a platform for
    computational chemists to implement algorithms in a
    platform-independent way.
  doc_url: http://cclib.github.io
  dev_url: https://github.com/cclib/cclib

extra:
  recipe-maintainers:
    - jaimergp
    - richardjgowers
    - berquist
    - langner
