{% set name = "cclib" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12b7a7ed8191f02fa12320dbdc830546ee1615e8b4737e3d766f34622abbd521

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - ccframe = cclib.scripts.ccframe:main
    - ccget = cclib.scripts.ccget:ccget
    - ccwrite = cclib.scripts.ccwrite:main
    - cda = cclib.scripts.cda:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy >=1.2.0
    - packaging >=19.0
    - pandas
    - periodictable
    - biopython
    # - openbabel (optional, not yet available on conda-forge)
    # - pyquante (optional, not yet available on conda-forge)

test:
  imports:
    - cclib
  commands:
    - ccframe --help
    - ccget --help
    - ccwrite --help

about:
  home: http://cclib.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parsers and algorithms for computational chemistry logfiles
  description: |
    cclib is a Python library that provides parsers for output files of
    computational chemistry packages. It also provides a platform for
    computational chemists to implement algorithms in a
    platform-independent way.
  doc_url: http://cclib.github.io
  dev_url: https://github.com/cclib/cclib

extra:
  recipe-maintainers:
    - jaimergp
    - richardjgowers
    - berquist
    - langner
