travis:
  secure:
    BINSTAR_TOKEN: oVugrrSY5AZdc+J7dompStDk73r0XN9qk8fSB9DKCDqAi496PLC0IErEz5kXE7e3cW2gWImbtm1LsQVQWNXrcOlYEuMRnliiJ4cNRzlHUuVJPX521G100+31nhFXB8AypIeLLdlJGk9fSLXDO5NQ5lCUB3lfPYyIDwqwqVm7wpPuC+deykB1xX4iLcuZ7OdYTydz7R81OwtwGt66TiSDaRY/9JzNMJeSTh8XQQS1l2qbpgpmCXeGmPLQO4OWuwUFWI9o4RQ4H4gZpAtx1QuiWMfYfKiXrqDfsR/nsGwfshkLsMm/ekDgJL05Mxxnt0vT2oRdTlDftbx3sy2kesX75OH5gv4j1cZJBc0xQXOiZgLOSZtPBl0FdXNKq8k+h7Qyj9yAzywyT/t17J2kMqVwtO4rF1MP30/XJaN2ijC3Z0FjUcp7WBjToTSCag+vGZZf8A8vtGn/icz0VZN17/J5VjWGrb8UcrdIs2qFShoyumoEcvOw1e+rsshzE/JiRRAnEXiMPB/9qlWMdUre9j2pIfcLMQVbMmn49vAEclJ4nssro+iudtwhPL+Odbumb15YBIJ48ayMtB5L3opFrFKZkir5UpSAxmXKRFwd7rELt1dnt5LexDetOUsXIvchEQ+6pAFSoY/XRTbnB5AzdK4V3MJaq1QtnQ/A8VsTaqosn5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
